const themes=[
['Anatomia','assets/anatomia.png','Detetives do Corpo Humano','Investigue estruturas reais/modelos e use o digital para lançar novas pistas.'],
['Segundo Cérebro','assets/segundo-cerebro.png','Missão Cérebro–Intestino','Explore a comunicação entre sistema nervoso e trato gastrointestinal sem simplificações.'],
['Anfiteatro','assets/anfiteatro.png','Game Show da Ciência','Perguntas abrem conversa; a explicação do estudante fecha cada rodada.'],
['Plantas Medicinais','assets/plantas.png','Detetive das Plantas','Observe, compare e investigue evidências. Natural não significa automaticamente seguro.'],
['Química','assets/quimica.png','Construtores de Moléculas','Do modelo físico à animação: forma, composição e caminho de uma substância.'],
['Digital','assets/digital.png','Agência de Ciência','Transforme o trabalho dos grupos em card, vídeo, convite e material acessível.']];
document.querySelector('#cards').innerHTML=themes.map(t=>`<article class="card"><img src="${t[1]}" alt="${t[0]}"><div><span class="kicker">${t[0]}</span><h3>${t[2]}</h3><p>${t[3]}</p></div></article>`).join('');
for(const id of ['bTema']) document.querySelector('#'+id).innerHTML=themes.map(t=>`<option>${t[0]}</option>`).join('');
function val(id){return document.getElementById(id).value.trim()||'a definir'}
function gerarChamada(){document.getElementById('saidaChamada').textContent=`TEMA: ${val('tema')}\nPÚBLICO: ${val('publico')}\nGANCHO: ${val('gancho')}\nDESCOBERTA: ${val('descoberta')}\nCONVITE: Venha explorar, experimentar e descobrir com a gente no MUDI — 8 e 15 de novembro de 2026.\n\nREVISÃO: linguagem clara • precisão científica • sem promessa de saúde • informação prática visível.`}
function montar(){const t=val('bTema'),p=val('participa'),f=val('fisico'),d=val('digital'),di=val('dinamica'),m=val('mediacao');document.getElementById('prot').textContent=`PROTÓTIPO — ${t}\n\nA criança: ${p.toLowerCase()}.\nRecurso físico: ${f}.\nDinâmica: ${di}.\nDigital: ${d.toLowerCase()}.\nEstudante de Medicina: ${m.toLowerCase()}.\n\nFluxo sugerido: explicação curta → missão → exploração física → desafio digital → feedback → nova descoberta.\n\nAntes da versão definitiva: conferir no MUDI o espaço, os objetos disponíveis, circulação, internet e segurança.`}
function promptArte(){document.getElementById('promptOut').textContent=`Criar cena ${val('formato')} de divulgação científica em 3D imersivo e semirrealista sobre ${val('pTema')}, ambientada em museu científico contemporâneo. Mostrar ${val('atividade')}. Visual acolhedor e atraente para crianças e famílias, porém não infantilizado; ciência como protagonista, iluminação cinematográfica, profundidade, cores vibrantes e elegantes, instalações interativas e sensação de descoberta. Anatomia educativa e não gráfica quando aplicável. Sem personagens caricatos, sem rostos em órgãos ou moléculas, sem marcas, sem logotipos e sem texto.`}
function copiar(id){navigator.clipboard?.writeText(document.getElementById(id).value)}function copiarTexto(id){navigator.clipboard?.writeText(document.getElementById(id).textContent)}
function ficha(){const html=`<h3>Ficha de Protótipo — Oficina MUDI 2026</h3><p><b>Tema:</b> ${val('bTema')}</p><p><b>Assunto científico:</b> ${val('tema')}</p><p><b>Gancho:</b> ${val('gancho')}</p><p><b>O que a criança verá fisicamente:</b> ${val('ver')}</p><p><b>O que fará:</b> ${val('fazer')}</p><p><b>O que a tecnologia acrescentará:</b> ${val('acrescenta')}</p><p><b>Brincadeira/desafio:</b> ${val('brinca')}</p><p><b>Como deverá sair da experiência:</b> ${val('saida')}</p><p><b>Chamada:</b> ${val('ctaFinal')}</p><hr><p><b>A confirmar no MUDI:</b> espaço físico, peças/modelos/materiais, circulação, equipamentos, internet e condições de acessibilidade.</p>`;document.getElementById('ficha').innerHTML=html}
let deferred;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;install.hidden=false});install?.addEventListener('click',async()=>{if(deferred){deferred.prompt();deferred=null;install.hidden=true}});if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
