const themes=[
['Anatomia','assets/anatomia.png','Detetives do Corpo Humano','Investigue estruturas reais/modelos e use o digital para lançar novas pistas.'],
['Segundo Cérebro','assets/segundo-cerebro.png','Missão Cérebro–Intestino','Explore a comunicação entre sistema nervoso e trato gastrointestinal sem simplificações.'],
['Anfiteatro','assets/anfiteatro.png','Game Show da Ciência','Perguntas abrem conversa; a explicação do estudante fecha cada rodada.'],
['Plantas Medicinais','assets/plantas.png','Detetive das Plantas','Observe, compare e investigue evidências. Natural não significa automaticamente seguro.'],
['Química','assets/quimica.png','Construtores de Moléculas','Do modelo físico à animação: forma, composição e caminho de uma substância.'],
['Digital','assets/digital.png','Agência de Ciência','Transforme o trabalho dos grupos em card, vídeo, convite e material acessível.']];
document.querySelector('#cards').innerHTML=themes.map(t=>`<article class="card"><img src="${t[1]}" alt="${t[0]}"><div><span class="kicker">${t[0]}</span><h3>${t[2]}</h3><p>${t[3]}</p></div></article>`).join('');
for(const id of ['bTema']) document.querySelector('#'+id).innerHTML=themes.map(t=>`<option>${t[0]}</option>`).join('');
function val(id){return document.getElementById(id).value.trim()||'a definir'}
function gerarChamada(){document.getElementById('saidaChamada').textContent=`TEMA: ${val('tema')}\nPÚBLICO: ${val('publico')}\nGANCHO: ${val('gancho')}\nDESCOBERTA: ${val('descoberta')}\nCONVITE: Venha explorar, experimentar e descobrir com a gente no MUDI — 8 e 15 de novembro de 2026.\n\nREVISÃO: linguagem clara • precisão científica • sem promessa de saúde • informação prática visível.`}
function montar(){const t=val('bTema'),p=val('participa'),f=val('fisico'),d=val('digital'),di=val('dinamica'),m=val('mediacao');document.getElementById('prot').textContent=`PROTÓTIPO — ${t}\n\nA criança: ${p.toLowerCase()}.\nRecurso físico: ${f}.\nDinâmica: ${di}.\nDigital: ${d.toLowerCase()}.\nEstudante de Medicina: ${m.toLowerCase()}.\n\nFluxo sugerido: explicação curta → missão → exploração física → desafio digital → feedback → nova descoberta.\n\nAntes da versão definitiva: conferir no MUDI o espaço, os objetos disponíveis, circulação, internet e segurança.`}
function promptArte(){document.getElementById('promptOut').textContent=`Criar cena ${val('formato')} de divulgação científica em 3D imersivo e semirrealista sobre ${val('pTema')}, ambientada em museu científico contemporâneo. Mostrar ${val('atividade')}. Visual acolhedor e atraente para crianças e famílias, porém não infantilizado; ciência como protagonista, iluminação cinematográfica, profundidade, cores vibrantes e elegantes, instalações interativas e sensação de descoberta. Anatomia educativa e não gráfica quando aplicável. Sem personagens caricatos, sem rostos em órgãos ou moléculas, sem marcas, sem logotipos e sem texto.`}
function copiar(id){navigator.clipboard?.writeText(document.getElementById(id).value)}function copiarTexto(id){navigator.clipboard?.writeText(document.getElementById(id).textContent)}
function ficha(){const html=`<h3>Ficha de Protótipo — Oficina MUDI 2026</h3><p><b>Tema:</b> ${val('bTema')}</p><p><b>Assunto científico:</b> ${val('tema')}</p><p><b>Gancho:</b> ${val('gancho')}</p><p><b>O que a criança verá fisicamente:</b> ${val('ver')}</p><p><b>O que fará:</b> ${val('fazer')}</p><p><b>O que a tecnologia acrescentará:</b> ${val('acrescenta')}</p><p><b>Brincadeira/desafio:</b> ${val('brinca')}</p><p><b>Como deverá sair da experiência:</b> ${val('saida')}</p><p><b>Chamada:</b> ${val('ctaFinal')}</p><hr><p><b>A confirmar no MUDI:</b> espaço físico, peças/modelos/materiais, circulação, equipamentos, internet e condições de acessibilidade.</p>`;document.getElementById('ficha').innerHTML=html}
let deferred;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;install.hidden=false});install?.addEventListener('click',async()=>{if(deferred){deferred.prompt();deferred=null;install.hidden=true}});if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');

const scienceThemes=themes.filter(t=>t[0]!=='Digital');
function sortearTema(){const t=scienceThemes[Math.floor(Math.random()*scienceThemes.length)];document.getElementById('sorteioOut').innerHTML=`<b>${t[0]} — ${t[2]}</b>\n${t[3]}\n\nTema temporário: use-o apenas para o exercício de hoje.`;document.getElementById('bTema').value=t[0];document.getElementById('pTema').value=t[0];}
const ideas={
'Anatomia':{gancho:'Você consegue descobrir qual estrutura do corpo está dando esta pista?',descoberta:'Explorar estruturas do corpo humano e relacionar forma, localização e função de maneira investigativa.',ver:'Modelos anatômicos, peças ou estruturas disponíveis no espaço — a confirmar no MUDI.',fazer:'Observar, comparar e procurar pistas para identificar uma estrutura.',acrescenta:'Liberar pistas, animações e desafios que complementem a observação do material físico.',brinca:'Caça científica: encontre a estrutura indicada e desbloqueie a próxima pista.'},
'Segundo Cérebro':{gancho:'O intestino e o cérebro realmente conversam?',descoberta:'Descobrir que cérebro, sistema nervoso e trato gastrointestinal mantêm comunicação complexa no organismo.',ver:'Modelos do cérebro e do sistema digestório — a confirmar no MUDI.',fazer:'Seguir pistas entre cérebro e intestino e comparar as informações encontradas.',acrescenta:'Animar sinais de comunicação e mostrar processos que não são visíveis no modelo físico.',brinca:'Missão cérebro–intestino: complete o caminho correto das pistas.'},
'Plantas Medicinais':{gancho:'Natural significa sempre seguro?',descoberta:'Investigar plantas, substâncias e evidências, diferenciando tradição, hipótese e conhecimento científico.',ver:'Plantas, folhas, amostras ou materiais disponíveis — a confirmar no MUDI.',fazer:'Observar características, comparar amostras e levantar hipóteses.',acrescenta:'Mostrar moléculas, ampliar detalhes e apresentar perguntas de investigação.',brinca:'Detetive das plantas: encontre a pista e decida “mito, dúvida ou evidência?”.'},
'Química':{gancho:'Como uma substância tão pequena pode interagir com o nosso corpo?',descoberta:'Relacionar modelos moleculares a propriedades e caminhos de substâncias no organismo.',ver:'Modelos moleculares ou materiais de demonstração — a confirmar no MUDI.',fazer:'Montar, comparar ou associar modelos e estruturas.',acrescenta:'Animar moléculas e representar processos microscópicos invisíveis a olho nu.',brinca:'Monte e descubra: complete o modelo para liberar a explicação.'},
'Anfiteatro':{gancho:'Qual hipótese você escolheria antes de ouvir a explicação?',descoberta:'Participar de perguntas científicas e construir a resposta com mediação dos estudantes.',ver:'Palco, placas, modelos ou recursos do anfiteatro — a confirmar no MUDI.',fazer:'Escolher respostas, justificar e participar da discussão.',acrescenta:'Registrar votos, mostrar resultados e liberar novas rodadas.',brinca:'Game show científico com perguntas, votação e explicação curta a cada rodada.'},
'Digital':{gancho:'Como transformar ciência em algo que dá vontade de descobrir?',descoberta:'Aprender a transformar conhecimento científico em comunicação visual clara, acessível e atraente.',ver:'A experiência e os materiais produzidos pelos grupos.',fazer:'Registrar, criar e testar diferentes formas de comunicação.',acrescenta:'Criar cards, vídeos, QR codes, animações e experiências digitais.',brinca:'Agência de ciência: transforme uma ideia em uma campanha curta para o público.'}}
function currentTheme(){return document.getElementById('bTema')?.value||'Anatomia'}
function iaCampo(id){const t=currentTheme(), data=ideas[t]||ideas.Anatomia;const map={gancho:'gancho',descoberta:'descoberta',ver:'ver',fazer:'fazer',acrescenta:'acrescenta',brinca:'brinca'};const el=document.getElementById(id);if(el)el.value=data[map[id]]||'';}
function direcionar(){const cam=document.getElementById('cameraUse').checked,mov=document.getElementById('movimentoFisico').checked,pts=document.getElementById('pontuacao').checked,exp=document.getElementById('explicar').checked;let tipo,desc;if(cam&&(mov||pts)){tipo='🎮 JOGO — Caça Científica com câmera';desc='Use a câmera como cenário, faça personagens/pistas aparecerem e, após cada captura, libere uma pergunta científica.'}else if(pts||mov){tipo='🎮 JOGO INTERATIVO';desc='Uma sequência de missões, pistas, pontuação e exploração física combina melhor com suas escolhas.'}else if(exp){tipo='🖥️ APRESENTAÇÃO INTERATIVA';desc='Organize o conteúdo em uma narrativa curta, com imagens, perguntas ao público e mediação do estudante.'}else{tipo='📱 APP / ESTAÇÃO DIGITAL';desc='Uma estação com escolhas, comparação, animações e conteúdo sob demanda combina melhor com a proposta.'}document.getElementById('direcaoOut').innerHTML=`<b>${tipo}</b>\n${desc}\n\nLembrete: a tecnologia deve acrescentar algo à experiência física, não substituí-la.`}
let stream=null,captures=0;
async function abrirCamera(){const msg=document.getElementById('cameraMsg');try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});document.getElementById('camera').srcObject=stream;msg.textContent='Câmera aberta. Toque em “Lançar personagem” e procure-o na tela.';}catch(e){msg.textContent='Não foi possível abrir a câmera. No celular, permita o acesso à câmera e use o site em HTTPS.'}}
function aparecerCriatura(){const c=document.getElementById('creature'),box=document.getElementById('cameraBox');const emojis=['🧬','🧠','🫀','🌿','⚗️','🔬'];c.textContent=emojis[Math.floor(Math.random()*emojis.length)];c.style.left=Math.max(8,Math.random()*(box.clientWidth-125))+'px';c.style.top=Math.max(8,Math.random()*(box.clientHeight-125))+'px';c.classList.add('show');document.getElementById('cameraMsg').textContent='Personagem lançado! Encontre-o na imagem e toque para capturar.'}
function capturar(){captures++;document.getElementById('captures').textContent=captures;document.getElementById('creature').classList.remove('show');const qs=['Pista científica liberada: explique em uma frase o que você encontrou.','Desafio: qual relação esse elemento pode ter com o tema sorteado?','Muito bem! Agora procure no espaço físico algo que ajude a explicar essa descoberta.'];document.getElementById('cameraMsg').textContent=qs[(captures-1)%qs.length]+(captures>=3?' Missão concluída!':'');}
